export default {
  'san-francisco-giants'  : { x: 3, y: 5 },
  'los-angeles-dodgers'   : { x: 4, y: 1 },
  'colorado-rockies'      : { x: 0, y: 4 },
  'arizona-diamondbacks'  : { x: 1, y: 0 },
  'san-diego-padres'      : { x: 2, y: 5 },
  'chicago-cubs'          : { x: 0, y: 1 },
  'st-louis-cardinals'    : { x: 4, y: 0 },
  'pittsburgh-pirates'    : { x: 2, y: 3 },
  'milwaukee-brewers'     : { x: 3, y: 2 },
  'cincinnati-reds'       : { x: 0, y: 2 },
  'washington-nationals'  : { x: 4, y: 5 },
  'miami-marlins'         : { x: 2, y: 2 },
  'new-york-mets'         : { x: 4, y: 2 },
  'philadelphia-phillies' : { x: 3, y: 3 },
  'atlanta-braves'        : { x: 0, y: 0 },
  'texas-rangers'         : { x: 1, y: 4 },
  'houston-astros'        : { x: 1, y: 2 },
  'seattle-mariners'      : { x: 3, y: 4 },
  'oakland-athletics'     : { x: 4, y: 4 },
  'los-angeles-angels'    : { x: 3, y: 1 },
  'cleveland-indians'     : { x: 0, y: 3 },
  'kansas-city-royals'    : { x: 2, y: 1, bg: '/stadiums/kansas-city-royals.jpg' },
  'detroit-tigers'        : { x: 1, y: 1, bg: '/stadiums/detroit-tigers.jpg' },
  'chicago-white-sox'     : { x: 0, y: 5 },
  'minnesota-twins'       : { x: 1, y: 5 },
  'baltimore-orioles'     : { x: 2, y: 0 },
  'boston-red-sox'        : { x: 3, y: 0, bg: '/stadiums/boston-red-sox.jpg' },
  'toronto-blue-jays'     : { x: 4, y: 3 },
  'new-york-yankees'      : { x: 1, y: 3 },
  'tampa-bay-rays'        : { x: 2, y: 4 },

}
