export default {
  'san-francisco-giants'  : { x: 3, y: 5, bg: 'http://www.googledrive.com/host/0BzRd-RDS5H-YNzhhSVN3RGVzYWM' },
  'los-angeles-dodgers'   : { x: 4, y: 1, bg: 'http://www.googledrive.com/host/0BzRd-RDS5H-YbUVUVkJaT0c3bXc' },
  'colorado-rockies'      : { x: 0, y: 4, bg: 'http://www.googledrive.com/host/0BzRd-RDS5H-YWUk2RWJ1TWtmUVk' },
  'arizona-diamondbacks'  : { x: 1, y: 0, bg: 'http://www.googledrive.com/host/0BzRd-RDS5H-YbTQxVGdqWEh6ejQ' },
  'san-diego-padres'      : { x: 2, y: 5 },
  'chicago-cubs'          : { x: 0, y: 1, bg: 'http://www.googledrive.com/host/0BzRd-RDS5H-YSVUtOXhSNjVMclk' },
  'st-louis-cardinals'    : { x: 4, y: 0 },
  'pittsburgh-pirates'    : { x: 2, y: 3 },
  'milwaukee-brewers'     : { x: 3, y: 2 },
  'cincinnati-reds'       : { x: 0, y: 2 },
  'washington-nationals'  : { x: 4, y: 5, bg: 'http://www.googledrive.com/host/0BzRd-RDS5H-YV0VsbzR4c19rTGc' },
  'miami-marlins'         : { x: 2, y: 2 },
  'new-york-mets'         : { x: 4, y: 2 },
  'philadelphia-phillies' : { x: 3, y: 3 },
  'atlanta-braves'        : { x: 0, y: 0 },
  'texas-rangers'         : { x: 1, y: 4, bg: 'http://www.googledrive.com/host/0BzRd-RDS5H-YRnpvY0xYUDNKaG8' },
  'houston-astros'        : { x: 1, y: 2, bg: 'http://www.googledrive.com/host/0BzRd-RDS5H-YWlJTT0d0QkRBcFk' },
  'seattle-mariners'      : { x: 3, y: 4, bg: 'http://www.googledrive.com/host/0BzRd-RDS5H-YM1FHWXN5T3pTOXc' },
  'oakland-athletics'     : { x: 4, y: 4 },
  'los-angeles-angels'    : { x: 3, y: 1 },
  'cleveland-indians'     : { x: 0, y: 3, bg: 'http://www.googledrive.com/host/0BzRd-RDS5H-YYm8yRk44VXdtNkU' },
  'kansas-city-royals'    : { x: 2, y: 1, bg: 'http://www.googledrive.com/host/0BzRd-RDS5H-YUXJyb1BIS2I4V28' },
  'detroit-tigers'        : { x: 1, y: 1, bg: 'http://www.googledrive.com/host/0BzRd-RDS5H-YSloyekxTS1F1UUE' },
  'chicago-white-sox'     : { x: 0, y: 5 },
  'minnesota-twins'       : { x: 1, y: 5 },
  'baltimore-orioles'     : { x: 2, y: 0, bg: 'http://www.googledrive.com/host/0BzRd-RDS5H-YZnVKZ0R0M1VPbDA' },
  'boston-red-sox'        : { x: 3, y: 0, bg: 'http://www.googledrive.com/host/0BzRd-RDS5H-YUzhCMFpseWQ0QXM' },
  'toronto-blue-jays'     : { x: 4, y: 3, bg: 'http://www.googledrive.com/host/0BzRd-RDS5H-YbjFRV2U4b3BpNFk' },
  'new-york-yankees'      : { x: 1, y: 3 },
  'tampa-bay-rays'        : { x: 2, y: 4 }
}
